-- NOTE: This migration was originally for Stripe-based subscription tables.
-- Stripe has been fully removed. Subscriptions are now handled by RevenueCat.
-- This file is kept as a placeholder. No tables are created here.
