-- ============================================
-- MIGRACIÓN: Características de TV para bares
-- Fecha: 2025-01-30
-- Objetivo:
--  - Crear tabla bar_tv_features para características de TV
--  - Crear tabla junction bar_selected_tv_features
--  - Poblar con datos iniciales de características de TV
-- ============================================

-- 1) Crear tabla de características de TV
CREATE TABLE IF NOT EXISTS public.bar_tv_features (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL UNIQUE,
  CONSTRAINT bar_tv_features_pkey PRIMARY KEY (id)
);

-- 2) Crear tabla de relación N:N entre bars y tv_features
CREATE TABLE IF NOT EXISTS public.bar_selected_tv_features (
  bar_id uuid NOT NULL,
  tv_feature_id integer NOT NULL,
  CONSTRAINT bar_selected_tv_features_pkey PRIMARY KEY (bar_id, tv_feature_id),
  CONSTRAINT bar_selected_tv_features_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id) ON DELETE CASCADE,
  CONSTRAINT bar_selected_tv_features_tv_feature_id_fkey FOREIGN KEY (tv_feature_id) REFERENCES public.bar_tv_features(id) ON DELETE CASCADE
);

-- 3) Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_bar_selected_tv_features_bar_id 
  ON public.bar_selected_tv_features(bar_id);

CREATE INDEX IF NOT EXISTS idx_bar_selected_tv_features_tv_feature_id 
  ON public.bar_selected_tv_features(tv_feature_id);

-- 4) Habilitar RLS (Row Level Security)
ALTER TABLE public.bar_tv_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bar_selected_tv_features ENABLE ROW LEVEL SECURITY;

-- 5) Policies para bar_tv_features (READ ONLY para todos los autenticados)
DROP POLICY IF EXISTS "bar_tv_features_select_all" ON public.bar_tv_features;
CREATE POLICY "bar_tv_features_select_all"
  ON public.bar_tv_features
  FOR SELECT
  TO authenticated
  USING (true);

-- 6) Policies para bar_selected_tv_features
-- SELECT: visible si el bar es visible (approved o el owner lo puede ver)
DROP POLICY IF EXISTS "bar_selected_tv_features_select_visible_bar" ON public.bar_selected_tv_features;
CREATE POLICY "bar_selected_tv_features_select_visible_bar"
  ON public.bar_selected_tv_features
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.bars b
      WHERE b.id = bar_selected_tv_features.bar_id
        AND (
          public.is_super_admin() 
          OR b.owner_id = auth.uid() 
          OR b.verification_status = 'approved'
        )
    )
  );

-- INSERT: solo el owner o admin puede añadir
DROP POLICY IF EXISTS "bar_selected_tv_features_insert_owner" ON public.bar_selected_tv_features;
CREATE POLICY "bar_selected_tv_features_insert_owner"
  ON public.bar_selected_tv_features
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.bars b
      WHERE b.id = bar_selected_tv_features.bar_id
        AND (public.is_super_admin() OR b.owner_id = auth.uid())
    )
  );

-- DELETE: solo el owner o admin puede eliminar
DROP POLICY IF EXISTS "bar_selected_tv_features_delete_owner" ON public.bar_selected_tv_features;
CREATE POLICY "bar_selected_tv_features_delete_owner"
  ON public.bar_selected_tv_features
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.bars b
      WHERE b.id = bar_selected_tv_features.bar_id
        AND (public.is_super_admin() OR b.owner_id = auth.uid())
    )
  );

-- 7) Poblar con características de TV iniciales
INSERT INTO public.bar_tv_features (name) VALUES
  ('Pantallas Gigantes'),
  ('Múltiples Pantallas'),
  ('Buena Calidad de Imagen'),
  ('Sonido Envolvente'),
  ('Audio Alto'),
  ('TV 4K'),
  ('Proyector de Gran Formato'),
  ('Transmisión en Vivo Garantizada')
ON CONFLICT (name) DO NOTHING;

-- 8) Grants
GRANT SELECT ON public.bar_tv_features TO authenticated;
GRANT SELECT ON public.bar_selected_tv_features TO authenticated;
GRANT INSERT, DELETE ON public.bar_selected_tv_features TO authenticated;

-- ============================================
-- FIN DE MIGRACIÓN
-- ============================================
